# Generated by Django 3.0.6 on 2020-05-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trangSuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.TextField()),
                ('nhom', models.TextField()),
                ('ten', models.TextField()),
                ('gia', models.TextField()),
                ('thongTinSP', models.TextField()),
                ('hinh', models.TextField()),
                ('boSuuTap', models.TextField(blank=True, null=True)),
                ('loaiDaChinh', models.TextField(blank=True, null=True)),
                ('mauDaChinh', models.TextField(blank=True, null=True)),
                ('hinhDangDa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.TextField()),
                ('nhom', models.TextField()),
                ('ten', models.TextField()),
                ('gia', models.TextField()),
                ('thongTinSP', models.TextField()),
                ('hinh', models.TextField()),
                ('boSuuTap', models.TextField(blank=True, null=True)),
                ('loaiDaChinh', models.TextField(blank=True, null=True)),
                ('mauDaChinh', models.TextField(blank=True, null=True)),
                ('hinhDangDa', models.TextField(blank=True, null=True)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trangSuc2.trangSuc')),
            ],
        ),
    ]
